POST http://localhost:3000/robots
Content-Type: application/json

{
    "robotName": "Mal",
    "robotType": "Dog",
    "bodyColour": "green",
    "faceColour": "white",
    "highlightColour": "yellow",
    "personality": "royal",
    "message": ["Hello World"],
    "dob": "2018-01-01",
    "price": 100000
}